# Generated by Django 4.0.4 on 2022-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_attendees_delete_event_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='gamers', to='levelupapi.gamer'),
        ),
    ]
