# Generated by Django 4.0.4 on 2022-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_rename_attendees_event_gamers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gamers',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='gamer', to='levelupapi.gamer'),
        ),
    ]
